Jeffrey branch
SACHSTech/grade-11-review---part-2-jeffrey-and-sam pull request #3
Opened 2020-11-26 16:04 UTC by jeffreylin-21

Added my half of the methods.

2020-11-26 16:07 UTC, samliu1234 commented on src/gr11review/part2/Main.java
> +    Utility.diagonal(8);
Make sure you delete this before handing it in

2020-11-26 16:08 UTC, samliu1234 commented on src/gr11review/part2/Utility.java
> +    intLength = str.length();
Maybe it's unnecessary to have a separate intLength variable?

2020-11-26 16:09 UTC, samliu1234 commented on src/gr11review/part2/Utility.java
> +    // Returns the total
You should probably put a space before the "return total" section

2020-11-26 16:14 UTC, samliu1234 requested changes
The functionality of the code looks okay. A few formatting changes here and there.

2020-11-26 16:14 UTC, samliu1234 commented on src/gr11review/part2/Utility.java
> +  // Returns an array where all instances of the selected value in the array are turned into its numerically highest neighbor
I think "numerically greater neighbor" fits better here

2020-11-26 16:14 UTC, samliu1234 commented on src/gr11review/part2/Utility.java
> +        if (nums[intCount-1] != nums[intCount] && nums[intCount+1] != nums[intCount]) {
Put a space before and after minus and plus signs

2020-11-26 16:14 UTC, samliu1234 commented on src/gr11review/part2/Utility.java
> +
Delete spaces in between

2020-11-27 14:09 UTC, jeffreylin-21 commented
@samliu1234 take another look please.

2020-11-29 17:06 UTC, merged